# Generated by Django 5.1.1 on 2024-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo_item",
            name="priority",
            field=models.CharField(
                choices=[("1", "LOW"), ("2", "MEDIUM"), ("2", "HIGH")]
            ),
        ),
    ]
