# Generated by Django 5.1.1 on 2024-09-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0010_alter_todo_item_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo_item",
            name="priority",
            field=models.CharField(choices=[("LOW", 1), ("MEDIUM", 2), ("HIGH", 3)]),
        ),
    ]
