# Generated by Django 5.1.1 on 2024-09-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0013_alter_todo_item_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo_item",
            name="priority",
            field=models.CharField(
                choices=[("1", "LOW"), ("2", "MEDIUM"), ("3", "HIGH")]
            ),
        ),
    ]
