# Generated by Django 5.1.1 on 2024-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0015_alter_todo_item_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo_item",
            name="test",
            field=models.CharField(default="hello", max_length=55),
            preserve_default=False,
        ),
    ]
