# Generated by Django 5.1.1 on 2024-09-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_todo_item_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_item',
            name='test',
        ),
    ]
