# Generated by Django 5.1.1 on 2024-09-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0019_todoitem_testing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="testing",
        ),
    ]
