# Generated by Django 5.1.1 on 2024-09-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0020_remove_todoitem_testing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="todoitem",
            name="category",
            field=models.ManyToManyField(blank=True, null=True, to="todo.category"),
        ),
    ]
