# Generated by Django 5.1.1 on 2024-09-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0023_remove_todoitem_category_todoitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
