# Generated by Django 5.1.1 on 2024-09-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0024_todoitem_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                max_length=20,
                null=True,
            ),
        ),
    ]
