# Generated by Django 5.1.1 on 2024-09-19 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0026_alter_todoitem_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="total_time_spent",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
