# Generated by Django 5.1.1 on 2024-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0027_todoitem_end_time_todoitem_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
