# Generated by Django 5.1.1 on 2024-09-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0028_todoitem_in_progress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="in_progress",
            new_name="timer_started",
        ),
    ]
