# Generated by Django 5.1.1 on 2024-09-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0029_rename_in_progress_todoitem_timer_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="progress",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
